### ISSUE TITLE
Missing arguments when building the basic emulator in README.md

### ISSUE THREAD

**Issue by antislava** [svanderburg/nix-androidenvtests#5]
Everything works but I had to add explicit arguments to the command for building the basic android emulator in Readme.md (it assumes the default values `["23"]` and `["x86"]` otherwise):
```
- $ nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a
+ $ nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a --arg emulatePlatformVersions '["16"]' --arg abiVersions '["armeabi-v7a"]'
```
(Also, I did quickly find your `nix-patchtools` repo but it should probably be referenced as a git submodule, or, rather, fetched from github in the `androidenv/default.nix`?)

**Comment by svanderburg** [comment]
@antislava Normally, you should use the Android SDK stuff in Nixpkgs. You can build against the upstream version by adding an additional parameter: `--arg useUpstream true`. Of course, this will only work once this pull request has been integrated: https://github.com/NixOS/nixpkgs/pull/50596

Alternatively, you can also clone the fork and build against that.

In the Nixpkgs version, I use the autopatchelfHook instead of the autopatchelf command in nix-patchtools, so you don't need anything else.

Did you have any problems with the default settings? For me it seems to work, but if you want to provide different or more exotic settings then you indeed have to adjust the parameters. That's how the Nix expression was developed. The idea is that you normally generate a Hydra jobset with all kinds of configuration settings. The default settings only provide a very simple basic testcase.

**Comment by antislava** [comment]
@svanderburg Thank you for the explanations (and for this work!). Everything just worked according to the `tests/README.md` (and BTW, I am talking about your  `nextgen` branch, of course, the `master` branch assumes some old `nixpkgs` version which is not specified and I didn't try to find a working one) after the two minor/obvious fixes I mentioned:
1. Cloning your `nix-patchelf` repo to satisfy the following import at `androidenv/default.nix:6`:
```
  autopatchelf = import ../../nix-patchtools;
```
2. Adding the respective arguments to 
```
nix-build -A emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a
```
, without which I'd get the following error
```
error: attribute 'emulate_16' in selection path 'emulate_myfirstapp_debug.host_x86_64-linux.build_16.emulate_16.armeabi-v7a' not found
```
(due to the fact that the current default arguments to `tests/deployment/default.nix` don't contain the emulated version `16` and `armeabi-v7a`).
